stages:
  - deploy
cache:
  paths:
    - node_modules/
deploy:
  image: docker:dind
  stage: deploy
  script:
    - docker build
    - docker run -d -p 3000:3000
  tags:
    - docker
  only:
    - master