stages:
  - deploy
cache:
  paths:
    - node_modules/
deploy:
  image: docker:dind
  stage: deploy
  script:
    - docker build -t app/blog .
    - docker run -d -p 3000:3000 --rm --name next-blog app/blog
  tags:
    - docker
  only:
    - master