stages:
  - deploy
cache:
  paths:
    - node_modules/
deploy:
  image: docker:dind
  stage: deploy
  script:
    - docker build -t app/codematica .
    - docker run -d -p 3000:3000 --rm --name codematica app/codematica
  tags:
    - docker
  only:
    - master